function fnIdiomaIngles(){
    document.getElementById("navbar-inicial").innerText = "Home"
    document.getElementById("navbar-imoveis").innerText = "Properties"
    document.getElementById("navbar-sobre").innerText = "About"
    document.getElementById("navbar-contato").innerText = "Contact"
    document.getElementById("hero-tx1").innerText = "Find your dream home"
    document.getElementById("hero-tx2").innerText = "Explore our wide range of properties and find the perfect home for you."
    document.getElementById("hero-tx3").innerText = "Search for properties"
    document.getElementById("hero-tx4").innerText = "Learn More"
    document.getElementById("contact-txt1").innerText = "Get in touch with us today!"
    document.getElementById("contact-txt2").innerText = "Contact Us"
    document.getElementById("contact-txt3").innerText = "Phone"
    document.getElementById("contact-txt4").innerText = "Office"
    document.getElementById("footer-txt1").innerText = "Subscribe to our newsletter for the latest updates on new features and product releases."
    document.getElementById("footer-txt2").innerText = "Subscribe"
    document.getElementById("rodape").innerText = "© 2025 Enzo Lanzi. All rights reserved."
}

function fnIdiomaPtBr(){
        document.getElementById("navbar-inicial").innerText = "Inicial"
        document.getElementById("navbar-imoveis").innerText = "Imóveis"
        document.getElementById("navbar-sobre").innerText = "Sobre nós"
        document.getElementById("navbar-contato").innerText = "Contato"
        document.getElementById("hero-tx1").innerText = "Encontre a casa dos seus sonhos"
        document.getElementById("hero-tx2").innerText = "Explore nossa ampla variedade de imóveis e encontre a casa perfeita para você."
        document.getElementById("hero-tx3").innerText = "Pesquise Imóveis"
        document.getElementById("hero-tx4").innerText = "Saiba Mais"
        document.getElementById("contact-txt1").innerText = "Entre em contato conosco hoje mesmo!"
        document.getElementById("contact-txt2").innerText = "Entre em contato"
        document.getElementById("contact-txt3").innerText = "Telefone"
        document.getElementById("contact-txt4").innerText = "Escritório"
        document.getElementById("footer-txt1").innerText = "Assine nossa newsletter para receber as últimas atualizações sobre novos recursos e lançamentos de produtos"
        document.getElementById("footer-txt2").innerText = "Cadastrar"
        document.getElementById("rodape").innerText = "© 2025 Enzo Lanzi. Todos os direitos reservados."
}